name: Run

on: workflow_dispatch

jobs:
  run:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run
      run: python main.py --log-level=info --output=data/
    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dataset
        path: data/
